//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace houseCRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCustomer
    {
        public int fCustomerId { get; set; }
        public string fCustomerName { get; set; }
        public System.DateTime fCustomerBirth { get; set; }
        public string fCustomerGender { get; set; }
        public string fCustomerEmail { get; set; }
        public string fCustomerAddress { get; set; }
        public string fCustomerPhone { get; set; }
    }
}
